[workspace]
members = ["proc", "other"]

[package]
name = "rust-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
other = { path = "other" }

[profile.release]
debug = "line-tables-only" # any non-"none" value will do
lto = "fat" # must be "fat"
panic = "abort" # not necessary
